# Generated by Django 5.2 on 2025-04-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_uet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='new', max_length=20),
        ),
    ]
